
CREATE TABLE  GUEST_ADDRESS (
	 GUEST_ADDRESS_ID   INT  PRIMARY KEY,
	 GUEST_PROFILE_ID   INT  NOT NULL,
	 ADDRESS_TYPE_ID   INT  NOT NULL,
	 ADDRESS_MASTER_ID   INT  NOT NULL,
	 REMARKS   VARCHAR2 (64) NULL,
	 IS_DEFAULT  CHAR NOT NULL,
	 IS_ACTIVE  CHAR NOT NULL,
	 CREATED_BY   VARCHAR2 (16) NOT NULL,
	 CREATED_ON   TIMESTAMP  NOT NULL,
	 MODIFIED_BY   VARCHAR2 (16) NOT NULL,
	 MODIFIED_ON   TIMESTAMP  NOT NULL,
	 CONSTRAINT GUEST_PROFILE3_FK
	 FOREIGN KEY(GUEST_PROFILE_ID)
	 REFERENCES GUEST_PROFILE(GUEST_PROFILE_ID),
     
	 CONSTRAINT ADDRESS_MASTER_FK
	 FOREIGN KEY(ADDRESS_MASTER_ID)
	 REFERENCES ADDRESS_MASTER(ADDRESS_MASTER_ID)
	 
);