CREATE TABLE APP_ROLE(
		APP_ROLE_ID INT PRIMARY KEY,
		PARENT_ID INT NULL,
		ROLE_NAME VARCHAR2(64) NOT NULL,
		ROLE_NAME_1 VARCHAR2(64) NOT NULL,
		DESCRIPTION VARCHAR2(256) NULL,
		IS_ACTIVE CHAR(1) NULL,
		CREATED_BY VARCHAR2(16) NOT NULL,
		CREATED_ON TIMESTAMP NOT NULL,
		MODIFIED_BY VARCHAR2(16) NOT NULL,
		MODIFIED_ON TIMESTAMP NOT NULL
	);