CREATE TABLE  APP_MASTER (
		 APP_MASTER_ID   INT PRIMARY KEY,
		 NAME   VARCHAR2 (128) NOT NULL,
		 DESCRIPTION   VARCHAR2 (128) NULL,
		 DEFAULT_URL   VARCHAR2 (512) NULL,
		 CREATED_BY   VARCHAR2 (16) NOT NULL,
		 CREATED_ON   TIMESTAMP   NOT NULL,
		 MODIFIED_BY   VARCHAR2 (16) NOT NULL,
		 MODIFIED_ON   TIMESTAMP   NOT NULL
	); 