CREATE TABLE APP_USER(
	APP_USER_ID INT PRIMARY KEY,
	APP_MASTER_ID INT NOT NULL,
	USER_NAME VARCHAR2(16) NOT NULL,
	FULL_NAME VARCHAR2(256) NULL,
	EMAIL VARCHAR2(256) NULL,
	EMAIL_CONFIRMED CHAR(1) NOT NULL,
	PASSWORD_HASH VARCHAR2(256) NULL,
	SECURITY_STAMP VARCHAR2(256) NULL,
	PHONE_NUMBER VARCHAR2(16) NOT NULL,
	PHONE_NUMBER_CONFIRMED CHAR(1) NOT NULL,
	TWO_FACTOR_ENABLED CHAR(1) NULL,
	LOCKOUT_END_DATE_UTC TIMESTAMP NULL,
	LOCKOUT_ENABLED CHAR(1) NULL,
	ACCESS_FAILED_COUNT INT NULL,
	IS_ACTIVE CHAR(1) NULL,
	CREATED_BY VARCHAR2(16) NULL,
	CREATED_ON TIMESTAMP NULL,
	MODIFIED_BY VARCHAR2(16) NULL,
	MODIFIED_ON TIMESTAMP NULL,
    CONSTRAINT APP_MASTER_FK
     FOREIGN KEY (APP_MASTER_ID)
     REFERENCES APP_MASTER(APP_MASTER_ID)
);