CREATE TABLE GUEST_PREFERENCES (
	 GUEST_PREFERENCES_ID   INT  PRIMARY KEY,
	 GUEST_PROFILE_ID   INT  NOT NULL,
	 PREFERENCE_ID   INT  NULL,
	 PREFERENCE_VALUE   VARCHAR2 (128) NULL,
	 REMARKS   VARCHAR2 (64) NULL,
	 CREATED_BY   VARCHAR2 (16) NOT NULL,
	 CREATED_ON   TIMESTAMP  NOT NULL,
	 MODIFIED_BY   VARCHAR2 (16) NOT NULL,
	 MODIFIED_ON   TIMESTAMP  NOT NULL,
     CONSTRAINT GUEST_PROFILE_FK
     FOREIGN KEY(GUEST_PROFILE_ID)
     REFERENCES GUEST_PROFILE(GUEST_PROFILE_ID)
);