CREATE TABLE  MEMBERSHIP (
	 MEMBERSHIP_ID   INT PRIMARY KEY,
	 MEMBERSHIP_TYPE_ID   INT  NULL,
	 DATE_FROM   TIMESTAMP  NULL,
	 DATE_TO   TIMESTAMP  NULL,
	 IS_ACTIVE   INT  NULL,
	 REMARKS   VARCHAR2 (256) NOT NULL,
	 CREATED_BY   VARCHAR2 (16) NOT NULL,
	 CREATED_ON   TIMESTAMP  NOT NULL,
	 MODIFIED_BY   VARCHAR2 (16) NOT NULL,
	 MODIFIED_ON   TIMESTAMP  NOT NULL
);