CREATE TABLE APP_USER_ROLE(
		APP_USER_ROLE_ID INT PRIMARY KEY,
		APP_USER_ID INT NOT NULL,
		APP_ROLE_ID INT NOT NULL,
		IS_ACTIVE CHAR(1) NOT NULL,
		CREATED_BY  VARCHAR2(16) NULL,
		CREATED_ON TIMESTAMP  NULL,
		MODIFIED_BY  VARCHAR2(16) NULL,
		MODIFIED_ON TIMESTAMP  NULL,
        CONSTRAINT APP_ROLE_FK
			FOREIGN KEY (APP_ROLE_ID)
			REFERENCES APP_ROLE(APP_ROLE_ID),
        CONSTRAINT APP_USER_FK
			FOREIGN KEY (APP_USER_ID)
			REFERENCES APP_USER(APP_USER_ID)
     );