CREATE TABLE ADDRESS_MASTER(
	ADDRESS_MASTER_ID INT PRIMARY KEY,
	ADDRESS_TYPE_ID INT NOT NULL,
	NAME VARCHAR2(128) NOT NULL,
	DESIGNATION INT NULL,
	CONTACT_NO_1 VARCHAR2(16) NULL,
	CONTACT_NO_2 VARCHAR2(16) NULL,
	EMAIL VARCHAR2(128) NULL,
	ADDRESS_1 VARCHAR2(128) NULL,
	ADDRESS_2 VARCHAR2(128) NULL,
	AREA VARCHAR2(128) NULL,
	CITY INT NULL,
	DISTRICT INT NULL,
	COUNTRY INT NULL,
	CREATED_BY VARCHAR2(16) NOT NULL,
	CREATED_ON TIMESTAMP NOT NULL,
	MODIFIED_BY VARCHAR2(16) NOT NULL,
	MODIFIED_ON TIMESTAMP NOT NULL
); 